-- Tables for InfraLink Events Application

-- 1. Users Table
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  two_factor_secret TEXT,
  two_factor_enabled INTEGER DEFAULT 0,
  reset_token TEXT,
  reset_token_expiry BIGINT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Page Content Table
CREATE TABLE IF NOT EXISTS page_content (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  section TEXT NOT NULL,
  key TEXT NOT NULL,
  value TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(section, key)
);

-- 3. Plans Table
CREATE TABLE IF NOT EXISTS plans (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  price DECIMAL(10, 2),
  period TEXT,
  features TEXT, -- Store as JSON string or text list
  badge_text TEXT,
  highlight_color TEXT,
  is_featured INTEGER DEFAULT 0,
  cta_text TEXT,
  cta_url TEXT,
  order_index INTEGER DEFAULT 0,
  budget_text TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Services Table
CREATE TABLE IF NOT EXISTS services (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  icon TEXT,
  order_index INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Customers Table
CREATE TABLE IF NOT EXISTS customers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  event_name TEXT,
  location TEXT,
  event_date TEXT,
  budget DECIMAL(15, 2),
  cost DECIMAL(15, 2),
  status TEXT DEFAULT 'Pendente',
  start_date TEXT,
  end_date TEXT,
  phone TEXT,
  email TEXT,
  plan_id INTEGER REFERENCES plans(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Inventory Table
CREATE TABLE IF NOT EXISTS inventory (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  brand TEXT,
  purchase_date TEXT,
  serial_number TEXT,
  supplier TEXT,
  price DECIMAL(15, 2),
  status TEXT DEFAULT 'Ativo',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. Plan Clicks (Analytics) Table
CREATE TABLE IF NOT EXISTS plan_clicks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plan_id INTEGER REFERENCES plans(id) ON DELETE CASCADE,
  day_of_week INTEGER,
  click_date DATE DEFAULT CURRENT_DATE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Row Level Security (RLS) - Example: Enable for all but require auth for writes
-- Note: You might need to adjust these based on your specific security requirements
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE page_content ENABLE ROW LEVEL SECURITY;
ALTER TABLE plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE services ENABLE ROW LEVEL SECURITY;
ALTER TABLE customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventory ENABLE ROW LEVEL SECURITY;
ALTER TABLE plan_clicks ENABLE ROW LEVEL SECURITY;

-- Simple public read policies (optional, adjust as needed)
CREATE POLICY "Public read page_content" ON page_content FOR SELECT USING (true);
CREATE POLICY "Public read plans" ON plans FOR SELECT USING (true);
CREATE POLICY "Public read services" ON services FOR SELECT USING (true);

-- Authenticated write policies
CREATE POLICY "Auth manage users" ON users ALL TO authenticated USING (true);
CREATE POLICY "Auth manage page_content" ON page_content ALL TO authenticated USING (true);
CREATE POLICY "Auth manage plans" ON plans ALL TO authenticated USING (true);
CREATE POLICY "Auth manage services" ON services ALL TO authenticated USING (true);
CREATE POLICY "Auth manage customers" ON customers ALL TO authenticated USING (true);
CREATE POLICY "Auth manage inventory" ON inventory ALL TO authenticated USING (true);
CREATE POLICY "Auth manage plan_clicks" ON plan_clicks ALL TO authenticated USING (true);
